FROM node:20-alpine

WORKDIR /app

COPY package.json yarn.lock ./
COPY apps/api/package.json ./apps/api/
COPY libs/database/package.json ./libs/database/
COPY libs/commons/package.json ./libs/commons/

EXPOSE 3000

CMD ["sh", "-c", "yarn install && yarn start:dev"]
